### ISSUE TITLE
Problems when testing the plugin

### ISSUE THREAD

**Issue by cgrabenstein** [cgrabenstein/intellij-phel-support#2]
This is a follow-up issue for the problems mentioned on the PR #1

**Comment by cgrabenstein** [comment]
![anim](https://user-images.githubusercontent.com/6358948/223214442-5d70762a-aa4e-4fe1-be53-0eb43e8345fc.gif)

@JesusValera I attached a video of the way it starts and works for me on your branch (now merged into main)

**Comment by JesusValera** [comment]
@cgrabenstein ok, it's working 🎉 

I was trying to open a `.phel` file inside the `phelplugin` project itself. I didn't try to create a new project.
Thank you so much 💃🏼
